sudo: no
dist: stretch
group: edge
language: generic
services:
  - docker

script:
  - >
    echo "$DOCKERHUB_PASSWORD" | docker login -u "maowtm" --password-stdin &&
    sudo apt-get install -y curl jq || exit 1;
    function doImage () {
      tag="$1";
      dockerfile="$2";
      lastupdatedtime="$(curl "https://registry.hub.docker.com/v2/repositories/$tag/tags/latest/" | jq -rj '.last_updated')" || return 1;
      if [ "$lastupdatedtime" != "null" ] && date -d "$lastupdatedtime"; then
        sincelastbuild=$[$(date +%s) - $(date -d "$lastupdatedtime" +%s)];
        if [ "$sincelastbuild" -le $[12*60*60] ]; then
          echo -e '\e[32m'Skipping image "$tag" because last build is only $[$sincelastbuild / 60 / 60] hours ago.'\e[0m'
          return 0;
        fi;
      fi;
      echo -e '\e[34m'Building image "$tag"...'\e[0m'
      docker build -f "$dockerfile" . -t "$tag";
      ret=$?;
      if [ $ret -ne 0 ]; then
        echo -e '\e[31m'Build failure on "$tag": docker build exited with code $ret.'\e[0m';
        return $ret;
      fi;
      if [ "$TRAVIS_BRANCH" = "master" ]; then
        echo -e '\e[34m'Pushing "$tag"'\e[0m';
        docker push "$tag";
        ret=$?;
        if [ $ret -ne 0 ]; then
          echo -e '\e[31m'Push failure on "$tag": docker push exited with code $ret.'\e[0m';
          return $ret;
        fi;
      else
        echo Skipping docker push on branch "$TRAVIS_BRANCH";
      fi;
      return 0;
    };
    cd docker-images &&
    doImage maowtm/archlinux-base-additions archlinux-base-additions.Dockerfile &&
    doImage maowtm/debian-stretch debian-stretch.Dockerfile &&
    doImage maowtm/v2ray v2ray.Dockerfile &&
    cd obfsproxy && doImage maowtm/obfsproxy Dockerfile && cd .. &&
    doImage maowtm/delegate delegate.Dockerfile &&
    cd desktop &&
    doImage maowtm/gtk gtk.Dockerfile &&
    doImage maowtm/vscode vscode.Dockerfile &&
    cd .. &&
    doImage maowtm/archlinux-texlive archlinux-texlive.Dockerfile; #
